/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing_sipariş_uygulaması;

import java.util.LinkedHashMap;
import java.util.Map;
import javax.swing.JOptionPane;

/**
 *
 * @author dkzn1
 */
public class Sipariş_Uygulaması extends javax.swing.JFrame {
    
    Map<String,Integer> siparişler = new LinkedHashMap<String,Integer>();

    /**
     * Creates new form Sipariş_Uygulaması
     */
    public Sipariş_Uygulaması() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        iskender = new javax.swing.JCheckBox();
        beyti = new javax.swing.JCheckBox();
        salata = new javax.swing.JCheckBox();
        ayran = new javax.swing.JCheckBox();
        sipariş_goster = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("MENÜ");

        iskender.setText("İskender - 15TL");

        beyti.setText("Beyti - 12TL");

        salata.setText("Salata - 5TL");
        salata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salataActionPerformed(evt);
            }
        });

        ayran.setText("Ayran - 2TL");

        sipariş_goster.setText("Siparişleri Göster");
        sipariş_goster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sipariş_gosterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(167, 167, 167)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ayran)
                    .addComponent(salata)
                    .addComponent(beyti)
                    .addComponent(iskender)
                    .addComponent(sipariş_goster, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(103, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(iskender)
                .addGap(18, 18, 18)
                .addComponent(beyti)
                .addGap(18, 18, 18)
                .addComponent(salata)
                .addGap(18, 18, 18)
                .addComponent(ayran)
                .addGap(18, 18, 18)
                .addComponent(sipariş_goster)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void salataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salataActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salataActionPerformed

    private void sipariş_gosterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sipariş_gosterActionPerformed
       
        if(iskender.isSelected()){
            siparişler.put("İskender",15);
        }
        else{
            siparişler.remove("İskender");
        }
        if(beyti.isSelected()){
            siparişler.put("Beyti",12);
        }
        else{
            siparişler.remove("Beyti");
        }
        if(salata.isSelected()){
            siparişler.put("Salata",5);
        }
        else{
            siparişler.remove("Salata");
        }
        if(ayran.isSelected()){
            siparişler.put("Ayran",2);
        }
        else{
            siparişler.remove("Ayran");
        }
        
        sipariş_goster();
        
        
        
        
    }//GEN-LAST:event_sipariş_gosterActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Sipariş_Uygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Sipariş_Uygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Sipariş_Uygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Sipariş_Uygulaması.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Sipariş_Uygulaması().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ayran;
    private javax.swing.JCheckBox beyti;
    private javax.swing.JCheckBox iskender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JCheckBox salata;
    private javax.swing.JButton sipariş_goster;
    // End of variables declaration//GEN-END:variables

    private void sipariş_goster() {
        
        String mesaj = "";
        int tutar = 0;
        
        if(siparişler.isEmpty()){
            mesaj = "Siparişiniz bulunmuyor..";
        }
        else{
            mesaj = "Siparişler\n";
            for(Map.Entry<String,Integer> entry : siparişler.entrySet()){
                mesaj += entry.getKey() + "\n";
                tutar += entry.getValue();
            }
            mesaj += "Toplam tutar = " +tutar;
        }
        
        JOptionPane.showMessageDialog(this, mesaj);
        
        
        
    }
}
