/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package swing_stok_uygulaması;

import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dkzn1
 */
public class Stok extends javax.swing.JFrame {

    /**
     * Creates new form Stok
     */
    public Stok() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mesaj_yazısı = new javax.swing.JLabel();
        tf_ürün = new javax.swing.JTextField();
        combo_kategori = new javax.swing.JComboBox<>();
        tf_fiyat = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        ürün_tablosu = new javax.swing.JTable();
        ekle_butonu = new javax.swing.JButton();
        güncelle_butonu = new javax.swing.JButton();
        sil_ürün = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ürün İsmi :");

        jLabel2.setText("Kategori :");

        jLabel3.setText("Fiyat : ");

        mesaj_yazısı.setForeground(new java.awt.Color(255, 51, 51));

        combo_kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kültür ve Sanat", "Elektrik" }));

        ürün_tablosu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Ürün İsmi", "Kategori", "Fiyat"
            }
        ));
        ürün_tablosu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ürün_tablosuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(ürün_tablosu);

        ekle_butonu.setText("ÜRÜN EKLE");
        ekle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ekle_butonuActionPerformed(evt);
            }
        });

        güncelle_butonu.setText("ÜRÜN GÜNCELLE");
        güncelle_butonu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                güncelle_butonuActionPerformed(evt);
            }
        });

        sil_ürün.setText("ÜRÜN SİL");
        sil_ürün.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil_ürünActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(tf_ürün, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(combo_kategori, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tf_fiyat))))
                        .addGap(78, 78, 78)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ekle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(güncelle_butonu, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE)
                            .addComponent(sil_ürün, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(mesaj_yazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(tf_ürün, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ekle_butonu))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(combo_kategori, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(güncelle_butonu))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(tf_fiyat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(sil_ürün)))
                .addGap(26, 26, 26)
                .addComponent(mesaj_yazısı, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ekle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ekle_butonuActionPerformed
        mesaj_yazısı.setText("");
        DefaultTableModel model = (DefaultTableModel) ürün_tablosu.getModel();

        if (tf_ürün.getText().trim().equals("")) {
            mesaj_yazısı.setText("Ürün ismi boş bırakılamaz...");
        } else {
            Object[] eklenecek = {tf_ürün.getText(), combo_kategori.getSelectedItem().toString(), tf_fiyat.getText()};
            model.addRow(eklenecek);
        }
    }//GEN-LAST:event_ekle_butonuActionPerformed

    private void güncelle_butonuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_güncelle_butonuActionPerformed

        mesaj_yazısı.setText("");
        DefaultTableModel model = (DefaultTableModel) ürün_tablosu.getModel();

        int seçili_row = ürün_tablosu.getSelectedRow();

        if (seçili_row == -1) {
            if (ürün_tablosu.getRowCount() == 0) {
                mesaj_yazısı.setText("Ürün tablosu şu anda boş...");
            } else {
                mesaj_yazısı.setText("Lütfen güncellenecek bir ürün seçiniz");
            }
        } else {
            model.setValueAt(tf_ürün.getText(), seçili_row, 0);
            model.setValueAt(combo_kategori.getSelectedItem().toString(), seçili_row, 1);
            model.setValueAt(tf_fiyat.getText(), seçili_row, 2);

            mesaj_yazısı.setText("Ürün güncellendi...");
        }


    }//GEN-LAST:event_güncelle_butonuActionPerformed

    private void ürün_tablosuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ürün_tablosuMouseClicked
        DefaultTableModel model = (DefaultTableModel) ürün_tablosu.getModel();

        int seçili_row = ürün_tablosu.getSelectedRow();

        tf_ürün.setText(model.getValueAt(seçili_row, 0).toString());
        combo_kategori.setSelectedItem(model.getValueAt(seçili_row, 1).toString());
        tf_fiyat.setText(model.getValueAt(seçili_row, 2).toString());


    }//GEN-LAST:event_ürün_tablosuMouseClicked

    private void sil_ürünActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sil_ürünActionPerformed
        
        mesaj_yazısı.setText("");
        
        DefaultTableModel model = (DefaultTableModel) ürün_tablosu.getModel();

        int seçili_row = ürün_tablosu.getSelectedRow();
        
        if(seçili_row == -1){
            if(ürün_tablosu.getRowCount() == 0){
                mesaj_yazısı.setText("Ürün tablosu şu anda boş...");
            }
            else{
                mesaj_yazısı.setText("Lütfen silinecek bir ürün seçiniz...");
            }
        }
        else{
            model.removeRow(seçili_row);
            mesaj_yazısı.setText("Ürün başarıyla silindi...");
                
        }


    }//GEN-LAST:event_sil_ürünActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> combo_kategori;
    private javax.swing.JButton ekle_butonu;
    private javax.swing.JButton güncelle_butonu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel mesaj_yazısı;
    private javax.swing.JButton sil_ürün;
    private javax.swing.JTextField tf_fiyat;
    private javax.swing.JTextField tf_ürün;
    private javax.swing.JTable ürün_tablosu;
    // End of variables declaration//GEN-END:variables
}
